### ISSUE TITLE
[Feature Request] Benchmarking

### ISSUE THREAD

**Issue by ilivans** [AmenRa/ranx#12]
**Is your feature request related to a problem? Please describe.**
To claim "blazing-fast", it would be nice to have benchmarks against existing implementations.

**Describe the solution you'd like**
The implementation is benchmarked against some/all of the sources below:
1. naive [numpy implementation](https://gist.github.com/bwhite/3726239/7e4dd612254e45fa275f9ddd9eb4af384a02794c)
2. [scikit-learn](https://github.com/scikit-learn/scikit-learn/) metrics module
3. [AstraZeneca/rexmex](https://github.com/AstraZeneca/rexmex)
4. [microsoft/rankerEval](https://github.com/microsoft/rankerEval)
5. [pytrec_eval](https://github.com/cvangysel/pytrec_eval)
6. ?

**Comment by AmenRa** [comment]
Hi, thank you for your interest in `ranx`!

I compared `ranx` against `pytrec_eval` for my ECIR paper, you can re-run the benchmark using this [notebook](https://github.com/AmenRa/ranx/blob/master/dev/efficiency_test.ipynb).

Here are the results reported in the ECIR paper that will be out in April:

![Screenshot 2022-02-16 at 15 26 36](https://user-images.githubusercontent.com/11797097/154285566-e458a316-1846-497b-bc45-8ffce55d0b39.png)

Adding a comprehensive comparison with other libraries is on my to-do list, but I have not had the time to do it yet.

Please, let me know what you think about the benchmark results.

Elias
