### ISSUE TITLE
[Feature Request] Reciprocal Rank Fusion

### ISSUE THREAD

**Issue by maximedb** [AmenRa/ranx#13]
Hi,

Thank you for this nice library.

How would you go about implementing [Reciprocal Rank Fusion](https://plg.uwaterloo.ca/~gvcormac/cormack) in ranx?

Thanks,

Maxime.

**Comment by AmenRa** [comment]
Hi Maxime and thanks for your question,

I plan to add many fusion methods to `ranx` this year, but I am currently busy with other projects.

Right now, your best bet is to implement `RRF` with Python dictionaries and pass the resulting fused run to `ranx `.

Alternatively, you can use an available Python implementation of `RRF` and convert the output to a data structure that can be loaded into `Ranx`.

Best,

Elias
