### ISSUE TITLE
[BUG] win_tie_loss in Report.to_dict

### ISSUE THREAD

**Issue by PaulLerner** [AmenRa/ranx#17]
**Describe the bug**

When converting a Report to dict, you only keep one `metric` while iterating over `metrics` (overwriting the previous `metric` in each loop)
https://github.com/AmenRa/ranx/blob/master/ranx/report.py#L315

**How to fix**
replace the line above with:
`d[m1]["win_tie_loss"][m2][metric] = self.win_tie_loss[(m1, m2)][metric]`
and init `d[m1]["win_tie_loss"][m2] = {}` at the same place as
https://github.com/AmenRa/ranx/blob/master/ranx/report.py#L309 (just above)

**Comment by AmenRa** [comment]
Well spotted, thanks!

Fixed in `v0.1.14`.
