### ISSUE TITLE
[BUG] from_ir_datasets seems to be missing from Qrels

### ISSUE THREAD

**Issue by cadurosar** [AmenRa/ranx#18]
**Describe the bug**
Qrels.from_ir_datasets("msmarco-document/dev") does not seem to work, it seems to have been removed by a commit 10 days ago. (https://github.com/AmenRa/ranx/commit/e0ca82c07392d90998b298515f48d0059c48c93d#)

**Comment by AmenRa** [comment]
Hi and thank you very much for pointing it out.
I must have used an old version of the code when I did the refactoring from the commit you mentioned, gotta check everything... :S

I restored "from_ir_datasets" in `v0.2.4`.

Thanks again!

**Comment by cadurosar** [comment]
Thanks a lot for this library, just came back after a while and this feature is pretty great, thanks for fixing it!

**Comment by AmenRa** [comment]
Super glad you like it! :D
Please, give it a star if you haven't yet and spread the word!
