### ISSUE TITLE
[Feature Request] optimize norm and method in optimize_fusion

### ISSUE THREAD

**Issue by PaulLerner** [AmenRa/ranx#33]
**Is your feature request related to a problem? Please describe.**
Instead of manually trying every possible fusion techniques, it’d be nice to be able to grid-search all of them, as `optimize_fusion` is already doing for fusion hyperparameters (e.g. weights in `wsum`).

**Describe the solution you'd like**
Allow to pass `List[str]` instead of `str` for `norm` and `method` parameters.
Then do something like:
```py
for norm in norms:
    for method in methods:
        optimize_fusion_current_behavior(*args, norm=norm, method=method, **kwargs)
```

The trick is to report the results in a readable manner.

**Comment by AmenRa** [comment]
I am aware of that, but I think the users should be aware of the normalization strategies and fusion methods they are using.
Therefore, I do not plan to add this feature any time soon.
