### ISSUE TITLE
[BUG] Could not find a version that satisfies the requirement ranx

### ISSUE THREAD

**Issue by celsofranssa** [AmenRa/ranx#34]
**Describe the bug**
Could not find a version that satisfies the requirement ranx (`pip3 install ranx`)

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

pip 21.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```

Error message:
```
ERROR: Could not find a version that satisfies the requirement ranx (from versions: none)
ERROR: No matching distribution found for ranx
```

**Comment by AmenRa** [comment]
This is not a bug, `ranx` requires Python >= 3.7.

**Comment by celsofranssa** [comment]
> This is not a bug, `ranx` requires Python >= 3.7.

Sorry, I could not find this requirement in the documentation.

**Comment by AmenRa** [comment]
No problem.
Python 3.7 is from mid-2018, that's why I did not write it down.
You can find all the requirements and dependencies in [setup.py](https://github.com/AmenRa/ranx/blob/master/setup.py).

**Comment by celsofranssa** [comment]
> No problem. Python 3.7 is from mid-2018, that's why I did not write it down. You can find all the requirements and dependencies in [setup.py](https://github.com/AmenRa/ranx/blob/master/setup.py).

I understand, but in addition to the ranx, a project is often composed of a set of packages (some requiring a specific Python version). Then, I'd like to suggest completing the documentation with the requirements.
