### ISSUE TITLE
question: why student rather than fisher stat test?

### ISSUE THREAD

**Issue by PaulLerner** [AmenRa/ranx#37]
Hi,

Just a quick question: I wondered what motivated the choice for changing the default value of the stat test to student instead of fisher https://github.com/AmenRa/ranx/commit/0dc8d9cf6b76ece0c8bccad267e2ce4f226127c3 (I almost published them as is before figuring it out :sweat_smile:).

I thought that one of your documentation pointed me to [this paper](https://dl.acm.org/doi/abs/10.1145/1321440.1321528) of Smucker et al. that suggests using Fisher (and especially not Student), but maybe I don’t recall correctly.

Btw, the docstring still shows 'fisher' as default https://amenra.github.io/ranx/compare/

**Comment by AmenRa** [comment]
Hey, I got a pull request for fixing the docs today :D

Student's and Fisher's tests very often agree (always?), but Student's is immensely faster to compute.
That's why I changed the default stat test.

The paper you mentioned says the opposite. From the introduction:

```
Student’s t, bootstrap, and randomization tests largely agree with each other.
Researchers using any of these three tests are likely to draw the same
conclusions regarding statistical significance of their results.
```

There's also a nice table showing that:
![Screenshot 2023-02-03 at 12 13 06](https://user-images.githubusercontent.com/11797097/216589561-58e1387f-2474-4664-9457-27b500cac368.png)

**Comment by PaulLerner** [comment]
This is the ‘practical’ conclusion with their experiments on TREC data. They have further discussion in §5.2 and in the end recommend to use Fisher’s randomization.

Thank you for your quick answer (as always :))

**Comment by AmenRa** [comment]
Sorry, I completely forgot about that section.

From my experiments on very different datasets from those used in the paper, Student's and Fisher's tests always agreed (comparing mean values).

I see the point about tiny test sets.
However, I question the validity of tiny test sets.
Are they representative of the general user behavior?
What's the confidence that a model outperforming another on a small set of queries will work better on different ones?
Is a small set of queries representative of the actual population of queries in the real world?

Obviously, we could be interested in testing a specific niche of queries depending on the use case.

What do you think about it?
