### ISSUE TITLE
[Feature Request] Expose DCG as metric

### ISSUE THREAD

**Issue by mpetri** [AmenRa/ranx#41]
In industry DCG (in both formulations) is a standard and widely used metric. I see it is already implemented as part of NDCG. Is it possible to expose it to the users as a real metric?

**Comment by AmenRa** [comment]
Hi, `dcg` is now available among the other metrics.
Please, update your `ranx` installation to `v0.3.13` to use it.

If you use `ranx` to evaluate results for your scientific publication, please remember to cite the related papers. Also, `GitHub` stars are much appreciated.

Thank you,

Elias

**Comment by mpetri** [comment]
Thank you for the quick response

**Comment by AmenRa** [comment]
You're welcome! ☺️
