### ISSUE TITLE
[Feature Request] Use black to indent the code

### ISSUE THREAD

**Issue by diegoceccarelli** [AmenRa/ranx#44]
**Is your feature request related to a problem? Please describe.**

`black` https://pypi.org/project/black/  is the Uncompromising Code Formatter. You can install it, run `black` and it will format the code properly. How about using it for the project in order to make sure style is consistent?

**Comment by AmenRa** [comment]
Hi Diego, the code was already `black` formatted.

The inconsistency was because I initially forced 80 chars line length in my IDE.
Then, I reverted it to 88 as suggested in `black` documentation but forgot to run `black` project-wise.

Now code formatting should be consistent.
