### ISSUE TITLE
question: relevance scores in Qrels

### ISSUE THREAD

**Issue by PaulLerner** [AmenRa/ranx#5]
Why is the relevance score mandatory in [Qrels](https://github.com/AmenRa/ranx/blob/master/ranx/qrels.py)?

I don’t see where you use it to compute the metrics https://github.com/AmenRa/ranx/blob/master/ranx/metrics.py

Is there any way to make it optional? If not, would a filler value like `0` for all documents be appropriate?

**Comment by AmenRa** [comment]
Hi, if you only have a list of relevant document ids but no relevance judgment, you should use `1` as relevance judgment score.

`0` relevance judgment scores are removed before computing metric scores to prevent miscomputations.

Among the implemented metrics only NDCG uses the relevance judgment scores. You can see it [here](https://github.com/AmenRa/ranx/blob/ab1467230e7bf658e8c335a291d9892dd052b7ca/ranx/metrics.py#L214).

By definition, all the other metrics consider relevance judgment scores to be binary even if they are not.

**Comment by PaulLerner** [comment]
Got it, thanks !
