### ISSUE TITLE
[Feature Request] Run.from_df and Run.from_parquet does not allow specifying run name

### ISSUE THREAD

**Issue by efung** [AmenRa/ranx#54]
**Is your feature request related to a problem? Please describe.**
I'm using Pandas dataframes, and comparing different embedding models. I'd like to be able to name my runs so when I compare them, the report shows something other than `run_1`, `run_2`.

**Describe the solution you'd like**
Allow `name` as a named parameter in `Run.from_df`

**Describe alternatives you've considered**
You can just set the name afterward, e.g.

```python
my_run.name = "My Run"
```

**Additional context**
I guess this is just for consistency, since `Run.from_file` allows you to pass a name.

**Comment by AmenRa** [comment]
Added in `v0.3.17`.

Please, give `ranx` a star if you haven't yet.
