### ISSUE TITLE
Question on rank aggregation usage

### ISSUE THREAD

**Issue by Wwwwei** [AmenRa/ranx#55]
Thanks for your amazing work. I am very interested in this framework and try to use it to solve my rank aggregation problems. However, I am a little confused about the usage.

For example, I have scores for several items under different ranking rules, as follows:
```
item | rank1 | rank2 | rank3
item1 | 0.4 | 0.8 | 0.2
item2 | 0.8 | 0.7 | 0.7
item3 | 0.7 | 0.7 | 1.0
item4 | 0.5 | 0.6 | 0.7
```
Now I want a comprehensive rank that satisfies all the subrank (e.g., rank1, rank2, rank3) constraints as much as possible.
```
item | rank
item1 | 0.5
item2 | 0.9
item3 | 0.7
item4 | 0.4
```
I'm not sure if that can be addressed with ranx. If so, could you show me an example?
Thanks a lot.

**Comment by AmenRa** [comment]
Hi, you can find an example on [Colab](https://colab.research.google.com/github/AmenRa/ranx/blob/master/notebooks/5_fusion.ipynb) and other information [here](https://amenra.github.io/ranx/fusion/).

As for your example, you could to something like this:

```python
from ranx import Run, fuse

run_1 = Run({"q1": {"item1": 0.4, "item2": 0.8, "item3": 0.7, "item4": 0.5}})
run_2 = Run({"q1": {"item1": 0.8, "item2": 0.7, "item3": 0.7, "item4": 0.6}})
run_3 = Run({"q1": {"item1": 0.2, "item2": 0.7, "item3": 1.0, "item4": 0.7}})

combined_run = fuse(runs=[run_1, run_2, run_3], method="max")

print(combined_run.to_dict()["q1"])
```

Output:

```python
{
    "item2": 0.048651507139079855,
    "item3": 0.04839549075403121,
    "item1": 0.047643442622950824,
    "item4": 0.047371031746031744,
}
```

**Comment by Wwwwei** [comment]
Thank you for your reply! it is very helpful and I will try it soon.
By the way, any suggestions for speeding up when the number of items and the subranks (e.g., tens of thousands of items and dozens of subranks) are both large?

**Comment by Wwwwei** [comment]
Thanks a lot. I got it.
