### ISSUE TITLE
Getting "Segmentation fault (core dumped)" error

### ISSUE THREAD

**Issue by sara-salamat** [AmenRa/ranx#56]
Hello,
Thank you for your amazing work. I am trying to use supervised fusion methods like this:
```python
best_params = optimize_fusion(
qrels=qrels,
runs=[run_4, run_5],
norm='min-max',  # Default value
method='posfuse',  
metric="mrr@10",  
)

combined_run = fuse(
runs=[run_4, run_5],
norm='min-max',  # Default value
method='posfuse',  # Alias for Weighted Sum
params=best_params,
)
``` 
I tried changing the norm and metric to every possible value but I still get "Segmentation fault (core dumped)" error.
I could not find any hints in the documentation about. sorry if I am missing something but can you help me with using these fusion methods?
thanks,

**Comment by AmenRa** [comment]
Hi and thanks for the kind words!

Can you tell me the OS you are using and the version of `numba` installed?
The issue is probably related to `numba`,  which is a library `ranx` heavily relies on.

**Comment by sara-salamat** [comment]
At first I was using an Ubuntu remote server (Ubuntu 20.04.6 LTS). I was getting that error for most of the approaches. I changed to macOS and now they are working fine! Thanks!
