### ISSUE TITLE
Integer relevance score

### ISSUE THREAD

**Issue by maximedb** [AmenRa/ranx#8]
Hi,

Thank you for this nice library.

Is there a fundamental reason why relevance score need to be integers in Qrels?

Thanks.

**Comment by AmenRa** [comment]
Hi and thank you! :)

In Information Retrieval, relevance score judgments can be binary or graded.
To the best of my knowledge, graded relevance score judgments are usually expressed as integers.

Moreover, if I recall correctly, the choice of requiring integers was taken for similarity with [`trec_eval`](https://github.com/usnistgov/trec_eval), the standard evaluation library in Information Retrieval.

Do you need`ranx` to support floating point relevance score judgments?

Best,

Elias

**Comment by maximedb** [comment]
Thank make sense! No no, it was just something I was wondering about :)

**Comment by Perenz** [comment]
Following up on this, I'd now need `ranx` to support floating point relevance score judgments?
Is that supported right now? Or is there a turnaround you'd recommend to use floating relevance score?

Best,

Stefano

**Comment by AmenRa** [comment]
Hi Stefano,

Are your

**Comment by AmenRa** [comment]
Hi Stefano,

I apologize if my question sounds stupid: are your relevance judgments truly continuous, or are they discrete but defined with floats?

In the latter case, you should always be able to convert them to integers by simply re-scaling them.

If that's not the case, you could, for example, round your floats at the 4th decimal position, multiply them by 10^4, and then cast them to integers.

If this still does not solve your problem, could you please provide more information about your use case so I can better help you find a solution?

I do not plan to change the implementation of Qrels at the moment.

Best,

Elias
